name: Update Jira Ticket to Ready To Build when passed review

on:
  pull_request_review:
    types: [submitted]

jobs:
  update_jira:
    runs-on: ubuntu-latest
    steps:
      - name: Check if review is approved
        if: github.event.review.state == 'approved'  # Proper indentation here
        run: |
          curl --request POST \
          --url https://ontrackretail.atlassian.net/rest/api/3/issue/${{ github.event.pull_request.head.ref }}/transitions \
          --user "maxwell.cochrane@ontrackretail.co.uk:${{ secrets.JIRA_API_KEY }}" \
          --header "Content-Type: application/json" \
          --data '{"transition": {"id": "101"}}'
